### ISSUE TITLE
Wrong diff page 122

### ISSUE THREAD

**Issue by sputnick-dev** [the-fast-track/book-5.0-1#11]
Hi,

In 10.7 page 110, the /conference route is `@Route("/conference/{id}", name="conference")`

In page 122, the route become `@Route("/conference/{slug}", name="conference")` with no edits in the meanwhile

**Comment by fabpot** [comment]
It is changed in the `Using Slugs in the Application` section of chapter 13.

**Comment by sputnick-dev** [comment]
It is page 128, 6 pages later of 122

**Comment by fabpot** [comment]
Can you give me the section headlines? Pages change depending on the version you are reading.
