### ISSUE TITLE
symfony book:checkout not working

### ISSUE THREAD

**Issue by flogalen** [the-fast-track/book-5.0-1#13]
When I run `symfony book:checkout 12 -vvv` I get the following: 

```
31/03 01:10:44 DEBUG     symfony  Auth token reloaded from /home/***/.symfony/auth.json
                                      
  unable to get the Git information:  
  exit status 1                       
                                      
                                      

Error trace:
                                      
  unable to get the Git information:  
  exit status 1                       
                                      
                                      

github.com/symfonycorp/symfony-cli/book.(*Book).CheckRepository
	github.com/symfonycorp/symfony-cli/book/reqs.go:26
github.com/symfonycorp/symfony-cli/cmd/symfony/commands.glob..func11
	github.com/symfonycorp/symfony-cli/cmd/symfony/commands/book_checkout.go:31
github.com/symfonycorp/symfony-cli/console.(*Command).Run
	github.com/symfonycorp/symfony-cli/console/command.go:167
github.com/symfonycorp/symfony-cli/console.(*Application).Run
	github.com/symfonycorp/symfony-cli/console/application.go:250
main.main
	symfony/main.go:102
runtime.main
	runtime/proc.go:203
runtime.goexit
	runtime/asm_amd64.s:1357

```

Since I ran into some issues with Symfony Cloud and wanted to make sure everything is correct I wanted to checkout the step 12. But unfortunately I'm stuck now and can't proceed with the book :(

**Comment by fabpot** [comment]
I've you tried to start from scratch in a clean directory? Does that work better?

**Comment by fabpot** [comment]
The error means that it was unable to run `git config --get remote.origin.url`. Can you try to run it manually? And copy/paste de content of `.git/config`?

**Comment by flogalen** [comment]
For some reason I had the remote part missing in my `.git/config`

```
[core]
	repositoryformatversion = 0
	filemode = true
	bare = false
	logallrefupdates = true
[symfony]
[symfony]
[symfony]
	cloud-project = sigetwvrl2bd6
```

I also wonder why there are 3 `[symfony]` tags in there. Might be the case due to deleting a project and creating a new one. Did that because right now I'm stuck at step 11-9 and can't proceed unfortunately. 

After I added the remote part it worked just fine again! What caused it to remove that from this file, I'm not aware of :(
