### ISSUE TITLE
branching chapter sessions-in-redis  - deployment issues

### ISSUE THREAD

**Issue by rileyrg** [the-fast-track/book-5.0-1#14]
Step 11 : branching the code. I updated the various config files, created an env, but when I try to 

symfony deploy 

with sessions-in-redis as my current branch I get:-

> guestbook   sessions-in-redis $ symfony deploy
>  
> Objekte aufzählen: 23, Fertig.
> Zähle Objekte: 100% (23/23), Fertig.
> Delta-Kompression verwendet bis zu 4 Threads.
> Komprimiere Objekte: 100% (12/12), Fertig.
> Schreibe Objekte: 100% (12/12), 1.68 KiB | 1.68 MiB/s, Fertig.
> Gesamt 12 (Delta 9), Wiederverwendet 0 (Delta 0)
>  
> Validating submodules
>  
> Validating configuration files
>  
> E: Error parsing configuration files:
>     - applications./.disk: Required
> To git.eu.s5y.io:zxobri65es6yg.git
>  ! [remote rejected] HEAD -> sessions-in-redis (invalid configuration files)
> error: Fehler beim Versenden einiger Referenzen nach 'zxobri65es6yg@git.eu.s5y.io:zxobri65es6yg.git'
>                                      
>   Deployment failed: Command failed  

Google was no help.

Any pointers?

**Comment by fabpot** [comment]
The error says that you have a configuration parsing error. Check your YAML files for typos.
