### ISSUE TITLE
symfony run bin/phpunit command don't find phpunit file

### ISSUE THREAD

**Issue by AlexandreCavanna** [the-fast-track/book-5.0-1#17]
Hello, 

I'm on windows 10 and when I try to execute `symfony run bin/phpunit`  Stage 17.1 Écrire des tests unitaires. 

I have an error exec: "bin/phpunit": file does not exist 
but I installed php unit with this command `symfony composer req phpunit` and he is in my bin folder.

For now I'm stuck with this.

Thanks for help.

**Comment by AlexandreCavanna** [comment]
Ok I find the solution on Windows to make it work we need to enter `symfony run \bin\phpunit`

**Comment by fabpot** [comment]
I've just realized that the command should be `symfony php bin/phpunit` instead of `symfony run bin/phpunit`. On *nix, both work (even if the version of PHP might not be the same), but on Windows only the first one will work. Can you confirm that `symfony php bin/phpunit` works well on Windows?

**Comment by AlexandreCavanna** [comment]
Yes it's work on Windows, thanks you for this info, it's always a bit shaky for me to convert command from unix or mac to Windows I must admit.
