### ISSUE TITLE
Warning needed for IDE files

### ISSUE THREAD

**Issue by jurriaanr** [the-fast-track/book-5.0-1#19]
PHP Storm is recommended (and rightly so) but the first time you execute git add . the .idea folder will be added as well. The book should contain a warning to add your IDE specific file/folder to the .gitignore file, instead it says everthing will be fine :)

**Comment by fabpot** [comment]
That's something that needs to be added in your main .gitignore file, not in the project one. In any case, that's out of the scope of the book.
