### ISSUE TITLE
Wrong github links

### ISSUE THREAD

**Issue by Nemecsek** [the-fast-track/book-5.0-1#2]
Hi.
There are some problems related to the Symfony 5 Fast Track book. 

Page 32, chapter 2.4, `https://githib.com/the-fast-track/5.0-1` is wrong. (real one ends with `/book-5.0-1`)
Page 32, footer link: `https://github.com/symfony/guestbook.example.com` does not work.

Please 
1) create these repositories to match the book ones
2) instead of using fixed URI, why not to use a shortened URLs next time or a dedicated "URL page" that can redirect you wherever you want? This would be far easier than fixed links 

Thanks

**Comment by gpirrotta** [comment]
Problem with the github link:
the command searches 
```https://github.com/the-fast-track/book-5.0.1```

but the repository name is
```https://github.com/the-fast-track/book-5.0-1```

![image](https://user-images.githubusercontent.com/2639616/74905583-d15a6a80-53ae-11ea-90b1-07a84da1d11a.png)

**Comment by fabpot** [comment]
These issues have been fixed in the text of the book.
