### ISSUE TITLE
Symfony cloud token expired

### ISSUE THREAD

**Issue by jurriaanr** [the-fast-track/book-5.0-1#20]
Perhaps not so much an issue for this book, but there was some time between me connecting to my symfony account for the cloud and running the first deployment.

Impossible to instantiate subservice cloud: Get https://symfony.com/api/services: oauth2: token expired and refresh token is not set 

As a tip it could say to use symfony login to reconnect

**Comment by fabpot** [comment]
Sorry you hit this bug. This should happen very rarely. I will see if we can improve the error message. Thanks for reporting.
