### ISSUE TITLE
Example app cannot be installed for PHP 7.4.1 in Windows

### ISSUE THREAD

**Issue by Nemecsek** [the-fast-track/book-5.0-1#3]
Hi.

Example app Guestbook cannot be installed because php_amqp.dll looks not compatible with Php 7.4.1 in Windows 10.

[RemiRepo](https://blog.remirepo.net/post/2019/05/23/PHP-extensions-status-with-upcoming-PHP-7.4) says **apqm 1.9.4** IS compatible with PHP 7.4 (May 2019)

[PECL](https://pecl.php.net/package/amqp/1.9.4) underlines the compatibility with PHP 7.3 only.<br>
[PECL Download links](https://pecl.php.net/package/amqp/1.9.4/windows) are only for PHP 7.3.

As stated [here](https://github.com/pdezwart/php-amqp/issues/362) the build for Windows is not available.

**Comment by diwms** [comment]
Maybe someone from community already solved that problem and have working binaries for php 7.4 and windows?

**Comment by fabpot** [comment]
I'm going to close this one as the issue comes from the AMQP lib, not from the code here.

**Comment by Nemecsek** [comment]
@fabpot, 
it is related to AMQP lib, but if I cannot install it the book's tutorial doesn't work and the book is virtually useless.

As an author you should care about compatibility (mostly when you use so many extensions), or provide docker containers, or VM images, or state clearly which limitations are involved. 

As Ia final user that paid to be guided by your book, I simply don't like this attitude that hide the problem under the carpet instead of helping searching for a workaround.

**Comment by Nemecsek** [comment]
To install AMQP, I followed the hint by j3App at [https://stackoverflow.com/questions/54967199/install-amqp-in-windows-10-php-7-3](https://stackoverflow.com/questions/54967199/install-amqp-in-windows-10-php-7-3):

1. download AMQP 1.9.4 from [https://pecl.php.net/package/amqp/1.9.4/windows](https://pecl.php.net/package/amqp/1.9.4/windows). To choose the proper version, _Thread safety_ can be checked with phpinfo()
2. extract `php_amqp.dll` and `php_amqp.pdb` in `c:\xampp\php\ext\` (or wherever the extension folder is)
3. extract `rabbitmq.4.dll` and `rabbitmq.4.pdb` into `c:\xampp\php\`
4. add `extension=amqp` to `php.ini`
5. restart Apache server.

**Comment by fabpot** [comment]
I don't hide anything. We the book was written, PHP 7.4 was not released. I could be not aware of the issue back then. I'm able to fix the extension myself either. What do you me to do?

**Comment by Nemecsek** [comment]
Fabien, it is understandable, but try to imagine what it means to buy a book to follow a tutorial to learn something new, and then to find broken steps. It is quite frustrating (mostly if to find a workaround is on my shoulders) and it means a lot of time lost wandering around to search for a viable solution among tons of outdated stackoverflow answers. 

The book is new and I would expect it works with any current version of PHP/package.
If is limited to PHP7.3 it should be stated somewhere.  

It is not the only glitch I found: after installing AMQP with the procedure I wrote above, even if `symfony book:check-requirements` returns OK, `bin/phpunit` is missing and `exit status` is 1. 

If I was you, I would give a look to various installations (at least the most common ones for both Windows and Linux), and see if they work properly according to your book.  

Please add on the book's page some info about installation, and the proper steps to have a working system to start with. Or provide a VM/Docker image, that perhaps is the easiest solution for you.

**Comment by AlexandreCavanna** [comment]
Nemecsek said it all.
