### ISSUE TITLE
Question about the book

### ISSUE THREAD

**Issue by philou69** [the-fast-track/book-5.0-1#5]
Hi.
First thanks for the book, it's awesome.

I don't if it's the good place for my questions but i don't know else where to send them.

My first question is about the symfony tool.

Every command you use in the book are made with `symfony console`.
 Why not simply using the `php bin/console` ?

My other question is about the entity `Conference`. 
The property   `isInternational ` is a boolean and is prefixed by `is`.

On the SymfonyInsight, there is a check that boolean property is not prefixed by is.

Wich way is the 'good' ?

Again thanks forthe book an thanks for the answers.

And sorry for my poor english.

**Comment by fabpot** [comment]
We are using `symfony console` so that we automatically get env vars set up depending on your Docker compose configuration or SymfonyCloud tunnels (this is explained at the beginning of the book).
