### ISSUE TITLE
without docker ?

### ISSUE THREAD

**Issue by SebSept** [the-fast-track/book-5.0-1#6]
The installation fails at docker step.
```
» symfony new --book guestbook --version 5.0-1
...
[WEB] Stopping Docker Containers: [ KO ]
Couldn't connect to Docker daemon at http+docker://localhost - is it running?

If it's at a non-standard location, specify the URL with the DOCKER_HOST environment variable.
```
It appears that my machine can not run docker for the moment (nor podman, neither docker/moby-engine).

I ran composer install & yarn install but then I have another error (Environment variable not found: "REDIS_URL".) I did try to fix it, I suppose the install process is not complete.

Is it possible to skip this docker step ?

**Comment by fabpot** [comment]
It's not possible to bypass the Docker check as the `new` command runs many commands to setup the project (including migrating the DB, ... which involves Docker).

**Comment by fabpot** [comment]
But, you can still clone the repository and work from there.

**Comment by SebSept** [comment]
ok. Thanks for feedback.
I'll do the config job by hand (will not be so hard, since debuging is easy with symfony).

**Comment by flogalen** [comment]
I had that issue as well, the reason being that your user lacks a group. 

`sudo usermod -a -G docker $USER`

after a reboot you now can run docker and everything works :)

**Comment by SebSept** [comment]
thanks for feedback but it does not work.
There is no pseudo docker daemon with podman.
(I'm reading the book and making an app without docker.)
